version: "3.2"
services:
  react-gauge-component:
    container_name: react-gauge-component
    build: ./
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 9010:3000
    stdin_open: true